### ISSUE TITLE
demo service fails

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#183]
Possible duplicate of #182

undefined is not a function
Path	
/api/v1/projects/demo_project/runs
Trace	
    at /opt/welder/api/welder_utility.js:402:4
    at /opt/welder/node_modules/async/lib/async.js:251:17
    at async.eachSeries (/opt/welder/node_modules/async/lib/async.js:142:20)
    at _asyncMap (/opt/welder/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/opt/welder/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/opt/welder/node_modules/async/lib/async.js:605:19)
    at Object.exports.danger.mkdir (/opt/welder/api/welder_utility.js:400:9)
    at /opt/welder/api/welder_runs.js:479:19
    at /opt/welder/node_modules/async/lib/async.js:607:21

**Comment by zsimpson** [comment]
CNR
