### ISSUE TITLE
unable to work with mongodb on a completely fresh install

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#20]
Here is the error stack. The collection in question is called "sessions", which i tried creating manually, but it didn't help. Tried a lot of other debugging too, but currently stuck.

```
/Users/ken/welder/node/node_modules/connect-mongo/lib/connect-mongo.js:134
          throw err;
                ^
TypeError: Cannot read property 'maxWriteBatchSize' of null
    at new ServerCapabilities (/Users/ken/welder/node/node_modules/mongodb/lib/topology_base.js:98:40)
    at Server.capabilities (/Users/ken/welder/node/node_modules/mongodb/lib/server.js:300:26)
    at Collection.listIndexes (/Users/ken/welder/node/node_modules/mongodb/lib/collection.js:1094:29)
    at Db.indexInformation (/Users/ken/welder/node/node_modules/mongodb/lib/db.js:1220:25)
    at Db.ensureIndex (/Users/ken/welder/node/node_modules/mongodb/lib/db.js:781:8)
    at Collection.ensureIndex (/Users/ken/welder/node/node_modules/mongodb/lib/collection.js:1133:13)
    at connectionReady (/Users/ken/welder/node/node_modules/connect-mongo/lib/connect-mongo.js:143:27)
    at Db.collection (/Users/ken/welder/node/node_modules/mongodb/lib/db.js:342:20)
    at initWithNativeDb (/Users/ken/welder/node/node_modules/connect-mongo/lib/connect-mongo.js:210:20)
    at process._tickCallback (node.js:355:11)
```

**Comment by zsimpson** [comment]
This is OSX I suppose?  Mongodb creates collections automatically so making them by hand shouldn't have helped. Maybe there's a version dependency on mongo and your OSX is different than the ubuntu one we're running?

**Comment by zsimpson** [comment]
This was the mongo session needed to be at exactly 0.8.0. They upgraded and it broke.
