### ISSUE TITLE
kayak_java needed restart

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#261]
GOT {"mykey4":25,"id":"baca568f-a80e-44d1-8b53-cba78cc3ac14","mykey3":false,"datetime":"2015-10-07T15:11:14.684Z","type":"demomessage","mykey2":11,"version":0.1}
Exception in thread "KayakSubscriptor22" CONNECTION CLOSED
org.java_websocket.exceptions.WebsocketNotConnectedException
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:566)
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:543)
        at com.appsoma.KayakJava.KayakSubscriber.run(KayakSubscriber.java:99)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kdemarest** [comment]
It was haproxy
