### ISSUE TITLE
Scaler process crashed on error checking partitions

### ISSUE THREAD

**Issue by vernonm** [appsoma/welder#301]
Happened while one broker (of 2) was crashed, and possibly before any data was written to a topic.
```
/welder/support/scaler/kascaler.js:258
				ingress += partitions[part].logSize - lastStatus.partitions[part].logSize;
				                                                                 ^
TypeError: Cannot read property 'logSize' of undefined
    at /welder/support/scaler/kascaler.js:258:71
    at ChildProcess.<anonymous> (/welder/support/scaler/kascaler.js:99:3)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5

```

**Comment by zsimpson** [comment]
I think this is resolved with extra check now
