### ISSUE TITLE
kascaler periodic exception

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#302]
Under normal operating conditions, kascaler periodically says:

/welder/support/scaler/kascaler.js:258
                                ingress += partitions[part].logSize - lastStatus.partitions[part].logSize;
                                                                                                 ^
TypeError: Cannot read property 'logSize' of undefined
    at /welder/support/scaler/kascaler.js:258:71
    at ChildProcess.<anonymous> (/welder/support/scaler/kascaler.js:99:3)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

**Comment by vernonm** [comment]
Duplicate of #301
